#Configuración para el servidor Tomcat
server:
  port: 8090

management.endpoints.web.exposure.include: "*"
#management.endpoints.web.exposure.exclude: loggers


spring:
  #Configuracion para el datasource
  datasource:
    url: jdbc:h2:file:c:/h2/bbddBorrar
    username: sa
    password:

  #Configuracion para JPA
  jpa:
    open-in-view: false    
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
