server:
  port: 9010

spring:
  application:
    name: "ServicioPedidos"

  datasource:
    url: jdbc:h2:file:c:/h2/bbdd_cloud_pedidos_BORRAR
    driverClassName: org.h2.Driver
    username: sa
    password: 
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect        
   
    