spring.application.name=Ej08_Spring_AI
spring.main.web-application-type=none

#https://console.groq.com/
spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

#0.0 muy serio, 1.0 muy creativo
spring.ai.openai.chat.options.temperature=0.7
